### ISSUE TITLE
Implement a sequence quality metric based on k-mer composition

### ISSUE THREAD

**Issue by hssn-20** [pinellolab/DNA-Diffusion#39] opened 2022-10-27 16:27 UTC

**Comment by lucapinello** [comment] 2022-10-27 19:01
@hssn-20 if you are still interested in implementing this. See: https://bioinfologics.github.io/post/2018/09/17/k-mer-counting-part-i-introduction/ this is based on Kat: https://github.com/TGAC/KAT
Briefly we can use the hist: Create an histogram of k-mer occurrences from a sequence file. Adds metadata in output for easy plotting.

**Comment by cameronraysmith** [comment] 2023-03-11 04:24
duplicate of #42

**Closed by cameronraysmith** 2023-03-11 04:24 UTC
Labels: notebook-prototyping, metrics
